<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.22000.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>Resources\Icons\app.ico</ApplicationIcon>
    <Copyright>anon5r</Copyright>
    <PackageIcon>icon256.png</PackageIcon>
    <StartupObject>KsGameLauncher2.Program</StartupObject>
    <Version>1.1.0.0</Version>
    <AssemblyVersion>1.1.0.0</AssemblyVersion>
    <FileVersion>1.1.0.0</FileVersion>
    <Product>Ks Game Launcher</Product>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>True</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Resources\app.ico" />
    <Content Include="Resources\Icons\app.ico" />
    <Content Include="Resources\Icons\default-game-icon.ico" />
    <Content Include="Resources\Icons\icon256.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AdysTech.CredentialManager" Version="3.1.0" />
    <PackageReference Include="AngleSharp" Version="1.8.2" />
    <PackageReference Include="Autoupdater.NET.Official" Version="1.9.3" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4191.47" />
    <PackageReference Include="Resource.Embedder" Version="2.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Forms\AboutForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\AccountForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\AddNewGameForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\LicensesForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\OptionsForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\OTPDialog.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="MainContext.resx.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="NotifyIconContextMenuStrip.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
    <Compile Update="Properties\Strings.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Strings.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Strings.en-US.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Properties\Strings.ja-JP.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Forms\AboutForm.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Update="MainContext.resx">
      <LastGenOutput>MainContext.resx.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Strings.en-US.resx">
      <SubType>Designer</SubType>
      <LastGenOutput>Strings.en-US.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Strings.ja-JP.resx">
      <SubType>Designer</SubType>
      <LastGenOutput>Strings.ja-JP.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Strings.resx">
      <SubType>Designer</SubType>
      <LastGenOutput>Strings.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <None Update="Resources\Icons\icon256.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>