//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KonaStaGameLauncher {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KonaStaGameLauncher.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Failed to remove account.\nYou can try removing it from &quot;Credential Manager&quot; in Control Panel.\nIf you click &quot;Retry&quot;, it will be open the &quot;Credential Manager&quot; window. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AccountRemoveFailed {
            get {
                return ResourceManager.GetString("AccountRemoveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Registered your account has been removed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AccountRemoveSucceeded {
            get {
                return ResourceManager.GetString("AccountRemoveSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Already running に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AlreadyRunning {
            get {
                return ResourceManager.GetString("AlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KonaSta Game Launcher に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Remove に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonRemove {
            get {
                return ResourceManager.GetString("ButtonRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Update に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonUpdate {
            get {
                return ResourceManager.GetString("ButtonUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Register に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonUpdate_Register {
            get {
                return ResourceManager.GetString("ButtonUpdate_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to exit ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmToExit {
            get {
                return ResourceManager.GetString("ConfirmToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove confirm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmToRemove {
            get {
                return ResourceManager.GetString("ConfirmToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to remove your account from the registered list ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmToRemoveAccountFromList {
            get {
                return ResourceManager.GetString("ConfirmToRemoveAccountFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter your account ID and password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EnterYourAccountPasswordPrompt {
            get {
                return ResourceManager.GetString("EnterYourAccountPasswordPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No account registered に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoAccountRegistered {
            get {
                return ResourceManager.GetString("NoAccountRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No installed games に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoInstalledGames {
            get {
                return ResourceManager.GetString("NoInstalledGames", resourceCulture);
            }
        }
    }
}
