//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KsGameLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KsGameLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon appIcon {
            get {
                object obj = ResourceManager.GetObject("appIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   anon に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AppIconDesigner {
            get {
                return ResourceManager.GetString("AppIconDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   account.konami.net に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AuthorizeDomain {
            get {
                return ResourceManager.GetString("AuthorizeDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ks Game Launcher に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CredentialTarget {
            get {
                return ResourceManager.GetString("CredentialTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon default_game_icon {
            get {
                object obj = ResourceManager.GetObject("default_game_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   anon に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Developers {
            get {
                return ResourceManager.GetString("Developers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   AdysTech.CredentialManager (https://github.com/AdysTech/CredentialManager) 
        ///
        ///HtmlAgilityPack (https://github.com/atifaziz/Hazz) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Licenses {
            get {
                return ResourceManager.GetString("Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M573SSID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoginCookieSessionKey {
            get {
                return ResourceManager.GetString("LoginCookieSessionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メンテナンス期間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MaintenanceCheckString {
            get {
                return ResourceManager.GetString("MaintenanceCheckString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KONAMI Amusement Inc.
        ///flaticon ( https://www.flaticon.com ) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SpecialThanks {
            get {
                return ResourceManager.GetString("SpecialThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Support に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SupportLabelText {
            get {
                return ResourceManager.GetString("SupportLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://github.com/anon5r/KsGameLauncher に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SupportLabelURL {
            get {
                return ResourceManager.GetString("SupportLabelURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /terms_of_service/index.html に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TosCheckPath {
            get {
                return ResourceManager.GetString("TosCheckPath", resourceCulture);
            }
        }
    }
}
