//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KsGameLauncher {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KsGameLauncher.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   About this に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AboutThisApp {
            get {
                return ResourceManager.GetString("AboutThisApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Account Manager に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AccountManagerForm {
            get {
                return ResourceManager.GetString("AccountManagerForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to remove account information.
        ///You can try removing it from &quot;Credential Manager&quot; in Control Panel.\nIf you click &quot;Retry&quot;, it will be open the &quot;Credential Manager&quot; window. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AccountRemoveFailed {
            get {
                return ResourceManager.GetString("AccountRemoveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Registered your account information has been removed from the app. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AccountRemoveSucceeded {
            get {
                return ResourceManager.GetString("AccountRemoveSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add new game に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddNewGameWindowTitle {
            get {
                return ResourceManager.GetString("AddNewGameWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;{0}&quot; is already exists に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AlreadyGameExists {
            get {
                return ResourceManager.GetString("AlreadyGameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Already running に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AlreadyRunning {
            get {
                return ResourceManager.GetString("AlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ks Game Launcher に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to authorize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AuthorizeFailed {
            get {
                return ResourceManager.GetString("AuthorizeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Remove に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonRemove {
            get {
                return ResourceManager.GetString("ButtonRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Update に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonUpdate {
            get {
                return ResourceManager.GetString("ButtonUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Re&amp;gister に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonUpdate_Register {
            get {
                return ResourceManager.GetString("ButtonUpdate_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not be saved game list, because not allowed write files. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CannotSaveGameList {
            get {
                return ResourceManager.GetString("CannotSaveGameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please check following page. (will open the web browser) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CheckFollowingPage {
            get {
                return ResourceManager.GetString("CheckFollowingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to add &quot;{0}&quot; ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmAddNewGame {
            get {
                return ResourceManager.GetString("ConfirmAddNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to exit ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmExitDialogMessage {
            get {
                return ResourceManager.GetString("ConfirmExitDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove confirm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmToRemove {
            get {
                return ResourceManager.GetString("ConfirmToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to logout your account from the registered List ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmToRemoveAccountFromList {
            get {
                return ResourceManager.GetString("ConfirmToRemoveAccountFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Network connection was time out. please check your network. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConnectionTimeout {
            get {
                return ResourceManager.GetString("ConnectionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Large に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContextMenuSize_Text_Large {
            get {
                return ResourceManager.GetString("ContextMenuSize_Text_Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Normal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContextMenuSize_Text_Normal {
            get {
                return ResourceManager.GetString("ContextMenuSize_Text_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drop shortcut here に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropHere {
            get {
                return ResourceManager.GetString("DropHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter your account ID and password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EnterYourAccountPasswordPrompt {
            get {
                return ResourceManager.GetString("EnterYourAccountPasswordPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to get the game defined file.
        ///This file may not exist or may be temporarily unavailable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorGetAppInfoFailed {
            get {
                return ResourceManager.GetString("ErrorGetAppInfoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error has occrred while login に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorWhileLogin {
            get {
                return ResourceManager.GetString("ErrorWhileLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to load {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedToLoadFile {
            get {
                return ResourceManager.GetString("FailedToLoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Terms of Service に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GameTermsOfServiceExceptionDialogName {
            get {
                return ResourceManager.GetString("GameTermsOfServiceExceptionDialogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Registered account に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GroupBoxAccountInfo {
            get {
                return ResourceManager.GetString("GroupBoxAccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Launching {0}... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IconBalloonMessage_Launching {
            get {
                return ResourceManager.GetString("IconBalloonMessage_Launching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login process... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IconBalloonMessage_WhileLogin {
            get {
                return ResourceManager.GetString("IconBalloonMessage_WhileLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Incorrect file format, please put &quot;Internet shortcut&quot; file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IncorrectFileFormat {
            get {
                return ResourceManager.GetString("IncorrectFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Incorrect username or password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IncorrectUsernameOrPassword {
            get {
                return ResourceManager.GetString("IncorrectUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Account ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelAccountID {
            get {
                return ResourceManager.GetString("LabelAccountID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game list size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelContextMenuSizeText {
            get {
                return ResourceManager.GetString("LabelContextMenuSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Developer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelDeveloper {
            get {
                return ResourceManager.GetString("LabelDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Icon desiner に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelIconDesigner {
            get {
                return ResourceManager.GetString("LabelIconDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Starting error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LauncherExceptionDialogName {
            get {
                return ResourceManager.GetString("LauncherExceptionDialogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Launcher URL has changed or is temporarily unavailable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LauncherURLCannotBeUsed {
            get {
                return ResourceManager.GetString("LauncherURLCannotBeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Licenses に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LicenseWindowTitle {
            get {
                return ResourceManager.GetString("LicenseWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoginExceptionDialogName {
            get {
                return ResourceManager.GetString("LoginExceptionDialogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login session has been expired. Please login again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoginSessionHasBeenExpired {
            get {
                return ResourceManager.GetString("LoginSessionHasBeenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No account registered に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoAccountRegistered {
            get {
                return ResourceManager.GetString("NoAccountRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No installed games に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoInstalledGames {
            get {
                return ResourceManager.GetString("NoInstalledGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This seems like a different shortcut に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotSupportedShortcut {
            get {
                return ResourceManager.GetString("NotSupportedShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display notification に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OptionsDisplayNotification {
            get {
                return ResourceManager.GetString("OptionsDisplayNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open proxy settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OptionsProxySettingsLink {
            get {
                return ResourceManager.GetString("OptionsProxySettingsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use proxy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OptionsUseProxyText {
            get {
                return ResourceManager.GetString("OptionsUseProxyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OptionsWindowTitle {
            get {
                return ResourceManager.GetString("OptionsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Service is temporarily down or unavailable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ServiceIsTemporaryUnavailable {
            get {
                return ResourceManager.GetString("ServiceIsTemporaryUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please setup your account from &quot;Manage account&quot; before launch app に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShouldBeSetAccountBeforeLaunch {
            get {
                return ResourceManager.GetString("ShouldBeSetAccountBeforeLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You should check terms of service for game, please check it. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShouldCheckTermOfService {
            get {
                return ResourceManager.GetString("ShouldCheckTermOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show confirm exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShowConfirmExit {
            get {
                return ResourceManager.GetString("ShowConfirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show licenses に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShowLicense {
            get {
                return ResourceManager.GetString("ShowLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game has been starting, please wait. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartngLauncher {
            get {
                return ResourceManager.GetString("StartngLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sync with server に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SynchWithServerButton {
            get {
                return ResourceManager.GetString("SynchWithServerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to sync with server?
        ///When you sync with the server, the games you manually registered will be initialized and will be as published on the server.  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SyncWithServerConfirmMessage {
            get {
                return ResourceManager.GetString("SyncWithServerConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sycn with server に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SyncWithServerDialogTitle {
            get {
                return ResourceManager.GetString("SyncWithServerDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Synchronization failed! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SyncWithServerFailedMessage {
            get {
                return ResourceManager.GetString("SyncWithServerFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Synchronization was successful! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SyncWithServerSuccessMessage {
            get {
                return ResourceManager.GetString("SyncWithServerSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown status received. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnknownStatusReceived {
            get {
                return ResourceManager.GetString("UnknownStatusReceived", resourceCulture);
            }
        }
    }
}
